HARD_FAILURE_CODES = {
    "NATIVE_TEXT_CORRUPT",
    "NATIVE_TEXT_MISSING",
    "READING_ORDER_INVALID",
    "BBOX_OUT_OF_BOUNDS",
    "BBOX_NON_POSITIVE_AREA",
    "TABLE_STRUCTURE_INVALID",
    "TABLE_EMPTY",
    "VISUAL_CROP_MISSING",
}

SOFT_FAILURE_CODES = {
    "PRINTABLE_RATIO_LOW",
    "REPLACEMENT_RATIO_HIGH",
    "DUPLICATE_LINES",
    "REPEATED_SYMBOLS",
    "OCR_TOO_SHORT",
    "EXCESSIVE_OVERLAP",
    "DUPLICATE_PARAGRAPHS",
    "TABLE_MARKDOWN_INVALID",
    "TABLE_HTML_INVALID",
    "TABLE_MISSING",
    "FORMULA_MISSING",
    "EXPECTED_FIGURE_MISSING",
    "VISUAL_BBOX_INVALID",
    "VISUAL_MEANING_MISSING",
}
